import React, { useEffect, useState } from 'react'
import SearchForm from '../components/SearchForm.js/SearchForm'
import UserList from '../components/list/UserList'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { useDispatch } from 'react-redux'
import { warehouseSliceActions } from '../../store/warehouseSlice'
import { useSelector } from 'react-redux';

export default function Home() {
  // const ISSERVER = typeof window === "undefined";
  // const isBrowser = () => typeof window !== "undefined";
  const router = useRouter()
  const authSelector = useSelector((state) => state.auth.auth)

  useEffect(() => {
    if (!localStorage.getItem('token')) {
      router.push('/login')
      return;
    }
  }, [])

  return (!authSelector ? <div></div> :
    <div className='bg-blue-500 w-full h-full min-h-screen   p-[36px]'>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta> */}
      </Head>
      <div className='text-white '>
        <div className='text-[32px] mb-[16px]'>Warehouses</div>
        <div className='mb-[40px]'>
          <SearchForm onChangeInput={searchInputHandle} onClickSearch={searchHandle} />
        </div>
        <div className='mb-[24px]'>
          <button onClick={() => router.push('/warehouse-management/add-warehouse')} className='text-[15px] block bg-transparent hover:opacity-80 border border-white cursor-pointer rounded-md min-w-[110px] h-[34px] px-[12px] py-[6px]'>Add warehouse</button>
        </div>
      </div>
      <div>
        <UserList />
      </div>
      {/* <div className='fixed bottom-0 left-[292px] right-[36px] h-[54px] border-t border-black'>
                <Save />
            </div> */}
    </div>
  )
}
