import React, { useState } from 'react'
import SearchForm from '../../components/SearchForm.js/SearchForm'
import { useRouter } from 'next/router'
import Head from 'next/head'
import SupplierList from '../../components/list/SupplierList'

function IoManagement() {

    const router = useRouter()

    return (
        <div className='bg-blue-500 w-full h-full min-h-screen   p-[36px]'>
            <Head>
                <title>in-out-management</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='text-white '>
                <div className='text-[32px] mb-[16px]'>Suppliers</div>
                <div className='mb-[40px]'>
                    <SearchForm />
                </div>
                <div className='mb-[24px]'>
                    <button onClick={() => router.push('/io-management/addSupplier')} className='text-[15px] mb-3 block bg-transparent hover:opacity-80 border border-white cursor-pointer rounded-md min-w-[110px] h-[34px] px-[12px] py-[6px]'>Add Supplier</button>
                    <button onClick={() => router.push('/io-management/ticket')} className='text-[15px] block bg-transparent hover:opacity-80 border border-white cursor-pointer rounded-md min-w-[110px] h-[34px] px-[12px] py-[6px]'>Tickets</button>
                </div>
            </div>
            <div>
                <SupplierList />
            </div>
            <div className='fixed bottom-0 left-[292px] right-[36px] h-[54px] border-t border-black'>
                {/* <Save /> */}
            </div>
        </div>
    )
}

export default IoManagement