import React, { useEffect, useState } from 'react'
import SearchForm from '../../components/SearchForm.js/SearchForm'
import WarehouseList from '../../components/list/WarehouseList'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { useDispatch } from 'react-redux'
import { warehouseSliceActions } from '../../store/warehouseSlice'
import { useSelector } from 'react-redux';


function WarehouseManagement() {

    const [searchInput, setSearchInput] = useState('')
    const authSelector = useSelector((state) => state.auth.auth)

    const router = useRouter()
    const dispatch = useDispatch()

    const searchInputHandle = (value) => {
        setSearchInput(value)
    }


    useEffect(() => {
        if (!localStorage.getItem('token')) {
            router.push('/login')
            return;
        }
    }, [])

    const searchHandle = async () => {
        try {
            const response = await fetch('https://scm-tool.thanhpp.ninja/storage')

            if (!response) {
                throw new Error('somethign wrong');
                return;
            }
            const data = await response.json()

            const dataSearched = data.data.filter((warehouse) => {
                if (warehouse.name.includes(searchInput) || warehouse.desc.includes(searchInput) || warehouse.location.includes(searchInput)) {
                    return true
                }
                return false
            })
            if (searchInput) {
                dispatch(warehouseSliceActions.isSearching({
                    data: true
                }))
            } else {
                dispatch(warehouseSliceActions.isSearching({
                    data: false
                }))
            }
            dispatch(warehouseSliceActions.warehouseSearch({
                data: dataSearched
            }))
            console.log(dataSearched)
        } catch (err) {
            console.log(err)
        }
    }

    return (authSelector ? <div></div> :
        //bg-[#1b1b38]
        <div className='bg-blue-500 w-full h-full min-h-screen   p-[36px]'>
            <Head>
                <title>warehouse-management</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='text-white '>
                <div className='text-[32px] mb-[16px]'>Warehouses</div>
                <div className='mb-[40px]'>
                    <SearchForm onChangeInput={searchInputHandle} onClickSearch={searchHandle} />
                </div>
                <div className='mb-[24px]'>
                    <button onClick={() => router.push('/warehouse-management/add-warehouse')} className='text-[15px] block bg-transparent hover:opacity-80 border border-white cursor-pointer rounded-md min-w-[110px] h-[34px] px-[12px] py-[6px]'>Add warehouse</button>
                </div>
            </div>
            <div>
                <WarehouseList />
            </div>
            {/* <div className='fixed bottom-0 left-[292px] right-[36px] h-[54px] border-t border-black'>
                <Save />
            </div> */}
        </div>
    )
}

export default WarehouseManagement